# Config file for automatic testing at travis-ci.org

language: python
dist: xenial
python:
  - "3.8"
  - "3.7"
  - "3.6"

  
os:
  - windows
  - linux
  - osx
  
  
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  
install: 
  - pip install -U tox-travis
  - pip install numpy
  - pip install coverage
  #- pip install flake8
  - pip install ".[test]"

script:
    - python setup.py install
    - tox


# after_success:
    # - codecov
  