name: ✨ Style

on: [push, pull_request]
#on:
  #pull_request:
    #branches:
      #- master
  #push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade setuptools pip wheel
        python -m pip install tox-gh-actions
        tox

    - name: Fix code style with isort (import calls)
      run: |
        python -m pip install isort
        isort pyllusion -l 120 --balanced --multi-line 3 --lines-between-types 1 --lines-after-imports 2 --trailing-comma

    - name: Fix code style with black (line lengths)
      run: |
        pip install black
        # The GitHub editor is 127 chars wide. See https://black.readthedocs.io/en/stable/installation_and_usage.html
        black pyllusion --line-length 120 .

    - name: Fix code style with docformatter (docstrings)
      run: |
        pip install docformatter
        # See https://github.com/myint/docformatter
        docformatter pyllusion --wrap-summaries 120 --wrap-descriptions 113 --blank --make-summary-multi-line --recursive

    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        message: "Commit style fixes"
        add: "*.py"
        cwd: "./pyllusion/"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
